### ISSUE TITLE
Mapa Mental web 3.0

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Luz1727#1]
[MapaMental-Web3.0-LuzArlethLB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Luz1727/files/14672168/MapaMental-Web3.0-LuzArlethLB.pdf)

**Comment by Irvingzr16** [comment]
Identificación del tema principal: 4 puntos
Contenidos/Conceptos: 4 puntos
Organización y estructura: 4 puntos
Formato: 4 puntos
Difusión: 4 puntos

Porcentaje obtenido: **20 puntos**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
